/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.akgs.algo.familytree;

import com.akgs.algo.familytree.common.AddChildFailedException;
import com.akgs.algo.familytree.common.AddSpouseFailedException;
import com.akgs.algo.familytree.common.PersonNotFoundException;
import com.akgs.algo.familytree.service.Command;
import com.akgs.algo.familytree.model.Female;
import com.akgs.algo.familytree.model.Male;
import com.akgs.algo.familytree.model.Person;
import com.akgs.algo.familytree.common.Constants;
import java.io.*;
import java.util.*;

/**
 * Initializes a family tree and evaluates and updates tree from given file
 */
public class FamilyTree {
    private Map<String, Person> people;

    public FamilyTree(String path) throws IOException, IllegalArgumentException {
        people = new HashMap<>();
        initialize();
        if(Objects.isNull(path) || path.isEmpty()){
            throw new IllegalArgumentException("No path argument passed.",new IOException("No path argument passed."));
        }
        processFile(path);
    }

    private void processFile(String path) throws IOException{
        processFile(new FileInputStream(new File(path)), true);
    }

    private void processFile(InputStream inputStream, Boolean print) throws IOException {
        BufferedReader br = new BufferedReader(new InputStreamReader(inputStream));
        String line = null;
        while((line = br.readLine()) != null){
            Command cmd = Command.parse(line);
            try {
                String out = cmd.evaluate(this);
                if(print){
                    System.out.println(out);
                }
            } catch (AddChildFailedException e) {
                if(print){
                    System.out.println(Constants.ADD_CHILD_FAILED);
                }
            } catch (PersonNotFoundException e) {
                if(print){
                    System.out.println(Constants.PERSON_NOT_FOUND);
                }
            } catch (AddSpouseFailedException e) {
                if(print){
                    System.out.println(Constants.ADD_SPOUSE_FAILED);
                }
            }
        }
    }

    private void initialize(){
        Female queen = new Female(Constants.DEFAULT_QUEEN, null);
        Male king = new Male(Constants.DEFAULT_KING, null);
        queen.addSpouse(king);
        people.put(Constants.DEFAULT_QUEEN, queen);
        people.put(Constants.DEFAULT_KING, king);
        try {
            InputStream inputStream = getClass().getResourceAsStream("/"+Constants.DEFAULT_TREE_FILE);
            processFile(inputStream, false);
        } catch (IOException e) {
        }
    }

    public Optional<Person> get(String name){
        return Optional.ofNullable(people.get(name));
    }

    public static void main(String[] args) {
        if (args.length < 1) {
            System.out.println("Invalid Input. file-path (containing family-tree building commands) argument required.");
            System.exit(1);
        }
        try {
            FamilyTree ft = new FamilyTree(args[0]);
        } catch (IOException e) {
            System.out.println("Error reading file");
        }
    }

    public void add(String name, Person person) {
        people.put(name, person);
    }
}
